// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package snapurl

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapshotRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	WaitPeriod           int32    `protobuf:"varint,2,opt,name=wait_period,json=waitPeriod,proto3" json:"wait_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *SnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotRequest.Unmarshal(m, b)
}
func (m *SnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotRequest.Marshal(b, m, deterministic)
}
func (m *SnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRequest.Merge(m, src)
}
func (m *SnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotRequest.Size(m)
}
func (m *SnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRequest proto.InternalMessageInfo

func (m *SnapshotRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SnapshotRequest) GetWaitPeriod() int32 {
	if m != nil {
		return m.WaitPeriod
	}
	return 0
}

type SnapshotResponse struct {
	SnapshotUrl          string   `protobuf:"bytes,1,opt,name=snapshot_url,json=snapshotUrl,proto3" json:"snapshot_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotResponse) Reset()         { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()    {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotResponse.Unmarshal(m, b)
}
func (m *SnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotResponse.Marshal(b, m, deterministic)
}
func (m *SnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotResponse.Merge(m, src)
}
func (m *SnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotResponse.Size(m)
}
func (m *SnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotResponse proto.InternalMessageInfo

func (m *SnapshotResponse) GetSnapshotUrl() string {
	if m != nil {
		return m.SnapshotUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*SnapshotRequest)(nil), "snapurl.SnapshotRequest")
	proto.RegisterType((*SnapshotResponse)(nil), "snapurl.SnapshotResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0xce, 0x4b, 0x2c, 0x28, 0x2d, 0xca, 0x91, 0x92,
	0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f,
	0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x93, 0x92, 0x44, 0x92, 0xcd, 0x28, 0x29, 0x29,
	0x48, 0xca, 0x4f, 0xa9, 0x84, 0x48, 0x29, 0xb9, 0x70, 0xf1, 0x07, 0xe7, 0x25, 0x16, 0x14, 0x67,
	0xe4, 0x97, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x97, 0x16, 0xe5,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0xf2, 0x5c, 0xdc, 0xe5, 0x89, 0x99,
	0x25, 0xf1, 0x05, 0xa9, 0x45, 0x99, 0xf9, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x5c,
	0x20, 0xa1, 0x00, 0xb0, 0x88, 0x92, 0x29, 0x97, 0x00, 0xc2, 0x94, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x45, 0x2e, 0x9e, 0x62, 0xa8, 0x58, 0x3c, 0xc2, 0x3c, 0x6e, 0x98, 0x58, 0x68, 0x51,
	0x8e, 0x51, 0x34, 0x17, 0x7b, 0x68, 0x90, 0x0f, 0x48, 0xa7, 0x50, 0x00, 0x17, 0x07, 0xcc, 0x04,
	0x21, 0x09, 0x3d, 0xa8, 0xb7, 0xf4, 0xd0, 0x9c, 0x26, 0x25, 0xa2, 0x07, 0xf1, 0x89, 0x1e, 0x28,
	0x08, 0x3c, 0x4a, 0x4a, 0x0a, 0x9c, 0xf2, 0x53, 0x2a, 0x95, 0x44, 0x9a, 0x2e, 0x3f, 0x99, 0xcc,
	0xc4, 0x27, 0xc4, 0xa3, 0x5f, 0x66, 0xa8, 0x0f, 0x33, 0x3f, 0x89, 0x0d, 0xec, 0x41, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x99, 0x50, 0x3d, 0x2f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// URLSnapClient is the client API for URLSnap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type URLSnapClient interface {
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
}

type uRLSnapClient struct {
	cc *grpc.ClientConn
}

func NewURLSnapClient(cc *grpc.ClientConn) URLSnapClient {
	return &uRLSnapClient{cc}
}

func (c *uRLSnapClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, "/snapurl.URLSnap/Snapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLSnapServer is the server API for URLSnap service.
type URLSnapServer interface {
	Snapshot(context.Context, *SnapshotRequest) (*httpbody.HttpBody, error)
}

// UnimplementedURLSnapServer can be embedded to have forward compatible implementations.
type UnimplementedURLSnapServer struct {
}

func (*UnimplementedURLSnapServer) Snapshot(ctx context.Context, req *SnapshotRequest) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}

func RegisterURLSnapServer(s *grpc.Server, srv URLSnapServer) {
	s.RegisterService(&_URLSnap_serviceDesc, srv)
}

func _URLSnap_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLSnapServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapurl.URLSnap/Snapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLSnapServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _URLSnap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snapurl.URLSnap",
	HandlerType: (*URLSnapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Snapshot",
			Handler:    _URLSnap_Snapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
